### ISSUE TITLE
'Nothing working services' 

### ISSUE THREAD

**Issue by myuksektepe** [posadskiy/currency-converter#4]
Caused by: com.posadskiy.currencyconverter.exception.CurrencyConverterException: Nothing working services. Please, try later again. If problem stay, create a ticket on github.com/posadskiy/currency-converter

I get this error when try to  use converter.rate() functions.

        val converter = CurrencyConverter(
            ConfigBuilder()
                .openExchangeRatesApiKey(CURRENCY_CONVERTER_API_API_KEY)
                .build()
        )

        val _rate: Double = converter.rate(Currency.USD, Currency.TRY)

        Log.i(TAG, "Rate is: ${_rate}")

I couldn't understand what about this error. Is library working still?

**Comment by posadskiy** [comment]
@myuksektepe probably, OpenExchangeRates.com is not worked when you tried to get a rate.
I can suggest you configure the others two services. This way, you get a rate in 100% cases.

Also, are you sure you used the correct API KEY? As I see, you configured service with constant with name from different service.

`.openExchangeRatesApiKey(CURRENCY_CONVERTER_API_API_KEY)
`
