### ISSUE TITLE
 Exchange rate update failed.

### ISSUE THREAD

**Issue by raviwaarr** [posadskiy/currency-converter#5]
Service CurrencyConverterApi.Com has problem now. Exchange rate update failed. from CLP to SGD last successful update = 01 Jan 1970 00:00:00:000 +0000

**Comment by posadskiy** [comment]
@raviwaarr Hi,

Thanks for the report.
This service could be off sometimes...
I see, now it's working.
Please, try again.

**Comment by posadskiy** [comment]
@raviwaarr 
Please, let us know if it helps you.
Thanks

**Comment by raviwaarr** [comment]
@posadskiy we need to have a way to configure API URL; We had to implement a different way to point to PAID/FREE URL.
